planner:
  prompt_file: planner_instructions_prompt_json.txt
  plan_format: json
coder:
  prompt_file: coder_instructions_prompt.txt
project:
  docker_image_name: unittest:example
  test_dir_in_container: /code/example/tests